import Header from "@/components/layout/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "@/components/Provider";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/layout/Footer";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hackathone one",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider>
          <Providers>
            <main className="px-28 py-5">
              <Header />
              {children}
              <Toaster />
              <Footer />
            </main>
          </Providers>
        </ClerkProvider>
      </body>
    </html>
  );
}
